name: Continuous Integration (Linux)

permissions:
  contents: write

on:
  push:
    paths:
      - 'CMakeLists.txt'
      - '.github/workflows/linux.yml'

jobs:
  build:
    name: Build container images
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, ubuntu-24.04-arm]
    runs-on: ${{ matrix.os }}
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-${{ matrix.os }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v4
      - name: Install build dependencies
        run: |
          sudo apt-get -qq update 
          sudo apt-get install -qqy \
            cmake \
            ninja-build \
            libx11-dev libxrandr-dev libxinerama-dev libgl1-mesa-dev libegl1-mesa-dev \
            libglu1-mesa-dev xorg-dev mesa-utils \
            libopenscenegraph-dev \
            libprotobuf-dev protobuf-compiler

      - run: |
          git clone https://github.com/OpenSimulationInterface/open-simulation-interface.git
          cd open-simulation-interface
          git checkout v3.5.0
          mkdir build
          cd build
          cmake ..
          make -j4
          sudo make install

      - name: CMake Configure - Default
        run: cmake --preset=ci-ubuntu_release -DUSE_OSG=0 -DUSE_OSI=1 -DUSE_SUMO=0 -DUSE_IMPLOT=0 -DUSE_GTEST=0

      - name: CMake Build
        run: cmake --build build --config Release --target install -j4
