name: Continuous Integration (Linux)

permissions:
  contents: write

on:
  push:
    paths:
      - 'CMakeLists.txt'
      - '.github/workflows/linux.yml'

jobs:
  build:
    name: Build container images
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, ubuntu-24.04-arm]
    runs-on: ${{ matrix.os }}
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-${{ matrix.os }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v4
      - name: Install build dependencies
        run: |
          sudo apt-get -qq update 
          sudo apt-get install -qqy \
            cmake \
            ninja-build

      - name: CMake Configure - Default
        run: cmake --preset=ci-ubuntu_release

      - name: CMake Build
        run: cmake --build build --config Release --target install -j4
